version: "3"
services:
  dynamodb-odm:
    image: dynamodb-odm:dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=1
      - AWS_SECRET_ACCESS_KEY=1
      - AWS_SESSION_TOKEN=1
      - DYNAMODB_ENDPOINT_URL=http://dynamodb-local:8000
    volumes:
      - .:/application
    depends_on:
      - dynamodb-local
    links:
      - dynamodb-local

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:1.21.0"
    container_name: dynamodb-local
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal