name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Composer install
        uses: php-actions/composer@v6
        with:
          php_version: 8.1
          php_extensions: bcmath

      - name: PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          php_version: 8.1
          path: src/
          standard: PSR2

      - name: Run PHP Spec
        uses: isbang/compose-action@v1.4.1
        with:
#          compose-file: "./docker-compose.yml"
          compose-flags: "run --no-deps dynamodb-odm vendor/bin/phpspec run"
